name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
    - 'v*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18

    - name: Check gofmt
      run: test -z "$(gofmt -s -d .)"

    - name: Run go vet
      run: go vet ./...

    - name: Make sure that go.mod has already been tidied
      run: go mod tidy && git diff --no-patch --exit-code

    - name: Build Habit Service
      run: go build ./cmd/habit-service

    - name: Build Progress Reporter
      run: go build ./cmd/progress-report

    - name: Run tests
      run: go test ./...
